src/AppBundle/Entity/Access.php
<?php


namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use AppBundle\Validator\Constraints as AppAssert;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Entity\AccessRepository")
 * @ORM\Table(name="access")
 */
class Access
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
  protected  $id;
    /**
     * @ORM\ManyToOne(targetEntity="Client", inversedBy="accesses")
     * @AppAssert\AccessClientConstraint
     */
  protected  $client;
    /**
     * @ORM\Column(type="integer")
     * @AppAssert\LockerConstraint
     */
  protected  $locker;
    /**
     * @ORM\Column(type="datetime")
     */
  protected  $startDate;
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
  protected  $endDate;


    /**
     * Access constructor.
     */
    public function __construct($client=null,$locker=null)
    {
        $this->startDate = new \DateTime();
        $this->client = $client;
        $this->locker = $locker;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set locker
     *
     * @param integer $locker
     * @return Access
     */
    public function setLocker($locker)
    {
        $this->locker = $locker;

        return $this;
    }

    /**
     * Get locker
     *
     * @return integer 
     */
    public function getLocker()
    {
        return $this->locker;
    }

    /**
     * Set startDate
     *
     * @param \DateTime $startDate
     * @return Access
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * Get startDate
     *
     * @return \DateTime 
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set endDate
     *
     * @param \DateTime $endDate
     * @return Access
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * Get endDate
     *
     * @return \DateTime 
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Set client
     *
     * @param \AppBundle\Entity\Client $client
     * @return Access
     */
    public function setClient(\AppBundle\Entity\Client $client = null)
    {
        $this->client = $client;

        return $this;
    }

    /**
     * Get client
     *
     * @return \AppBundle\Entity\Client 
     */
    public function getClient()
    {
        return $this->client;
    }


    public function getElapsedTime(){

       $diff = null;
        if($this->getEndDate()){
            $diff = $this->getEndDate()->diff($this->getStartDate());
        }else{
            $now = new \DateTime();
            $diff = $now->diff($this->getStartDate());
        }

        return  $diff;
    }
}

src/AppBundle/Controller/DashboardController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Client;

class DashboardController extends Controller
{
    /**
     * @Route("/", name="dashboard")
     * @Method("GET")
     * @Template()
     */
    public function indexAction(Request $request)
    {

        $em = $this->getDoctrine()->getManager();
        $accesses = $em->getRepository('AppBundle:Access')->findTodayAccesses();
        $anonyAccesses = $em->getRepository('AppBundle:SpecialAccess')->findTodayAccesses();
        $em = $this->getDoctrine()->getManager();
        $pending = $em->getRepository('AppBundle:Client')->findBy(array('cardNumber'=>null,'state'=>Client::STATE_PENDING),null, 50,0);

        return array(
            'accesses' => $accesses,
            'anonyAccesses' => $anonyAccesses,
            'pending' => $pending
        );

    }



}

src/AppBundle/Resources/views/Dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block resfresh %}<meta http-equiv="refresh" content="300">{% endblock %}
{% block body %}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Dashboard</h1>
        </div>
    </div>
    <div class="row">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-list fa-fw"></i> Socios pendientes de activiar
                    </div>
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <th>Tipo Documento</th>
                                <th>Nª Documento</th>
                                <th>Nombre</th>
                                <th>Apellidos</th>
                                <th>E-mail</th>
                                <th>Actions</th>
                                </thead>
                                <tbody>

                                {% for client in pending %}
                                    <tr class="even gradeC">
                                        <td>{{ client.idCardType|idType }}</td>
                                        <td>{{ client.idCardNumber }}</td>
                                        <td>{{ client.name }}</td>
                                        <td>{{ client.surname }}</td>
                                        <td>{{ client.email }}</td>
                                        <td>
                                            <a class="btn btn-primary"
                                               href="{{ path('client_edit', { 'id': client.id }) }}">
                                                <i class="fa fa-edit"></i>Activar</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-users fa-fw"></i> Actualmente en el local
                        <div class="pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle"
                                        data-toggle="dropdown">
                                    Acciones
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="{{ path("access") }}">Ver todos</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-bordered table-hover table-striped">
                                    <thead>
                                    <tr>
                                        <th>Socio</th>
                                        <th>Taquilla</th>
                                        <th>Fecha entrada</th>
                                        <th>Fecha Salida</th>
                                        <th>Tiempo</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for access in accesses %}
                                        <tr>
                                            <td>
                                                <a href="{{ path('client_edit', { 'id': access.id }) }}">{{ access.client }}</a>
                                            </td>
                                            <td>{{ access.locker }}</td>
                                            <td>{% if access.startDate %}{{ access.startDate|date('d-m-Y H:i:s') }}{% endif %}</td>
                                            <td>{% if access.endDate %}{{ access.endDate|date('d-m-Y H:i:s') }}{% endif %}</td>
                                            <td>{{ computeTime(access.elapsedTime) }}</td>
                                        </tr>
                                    {% endfor %}

                                    {% for access in anonyAccesses %}
                                        <tr>
                                            <td>Anónimo</td>
                                            <td>{{ access.locker }}</td>
                                            <td>{% if access.startDate %}{{ access.startDate|date('d-m-Y H:i:s') }}{% endif %}</td>
                                            <td>{% if access.endDate %}{{ access.endDate|date('d-m-Y H:i:s') }}{% endif %}</td>
                                            <td>{{ computeTime(access.elapsedTime) }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

<div class="modal fade" id="clientModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalLabel">Datos del socio</h4>
            </div>
            <div class="modal-body">
                <div class="panel panel-default">
                    <div class="panel-body">

                <a id="modal-user"class="btn btn-primary" role="button" data-toggle="collapse" href="#clienformdata" aria-expanded="false" aria-controls="clienformdata">
                    Mostrar
                </a>
                <div class="collapse" id="clienformdata"></div>
                        <div id="client-status-message" class="alert hidden" role="alert">

                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div id="status-message" class="alert hidden" role="alert">

                        </div>
                    <form  id="lockerForm" class="form-inline">
                        <div class="form-group">
                            <label for="lockerNumber">Nº Taquilla</label>
                            <input type="number" class="form-control" id="lockerNumber" placeholder="Numero de taquilla">
                        </div>
                        <button id="assignButton" type="button" class="btn btn-primary">Asignar</button>
                    </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">


        $(document).ready(function() {

            $(this).scannerDetection({
                timeBeforeScanTest: 200, // wait for the next character for upto 200ms
                startChar: [120], // Prefix character for the cabled scanner (OPL6845R)
                endChar: [13], // be sure the scan is complete if key 13 (enter) is detected
                avgTimeByChar: 40, // it's not a barcode if a character takes longer than 40ms
                onComplete: function(barcode, qty) {
                    var client;

                    $.get("/api/v1/client/membercard/"+trimNumber(barcode), function (data) {

                    }).done(function (data) {
                        if (!data.status != 200 ) {
                            client = data.data
                            $("#clienformdata").load("/client/form/" + client.id);
                            $("#modal-user").text(client.name + " "+client.surname);
                            $('#clientModal').modal('show');
                            $(document).scannerDetection(false);
                        } else {
                            alert(errorMsg);
                        }
                    }).fail(function (data) {
                        alert("No se ha encontrado un socio con tarjeta :"+trimNumber(barcode));
                    });
                }
            });
            $('#clientModal').on('shown.bs.modal', function () {
                $('#lockerNumber').focus()
            })

            $('#clientModal').on('hidden.bs.modal', function () {
                location.reload();
            })

            $("#assignButton").on("click", function(e) {
              assignLocker("client_cardNumber","lockerNumber");
            });

            $(window).keydown(function(event){
                if(event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });
        })
    </script>

{% endblock %}

src/AppBundle/Resources/views/Dashboard/welcome.html.twig
{% extends '::welcome.html.twig' %}

{% block body -%}


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-user fa-fw"></i> Registrate
            </div>
            <div class="panel-body">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class=" col-lg-8 col-md-offset-4">
                        <div class="col-lg-6 ">
                            <div class="panel panel-primary">
                                <a href="{{ path("client_register") }}">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-lg-2">
                                                <i class="fa fa-user  fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge">Nueva cuenta</div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}